### ISSUE TITLE
Contraceptive use barriers - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#101]
Array of distribution of reasons for non-use. 

Assigned to all agents though not being used currently. Needs to be updated for new country context.

**Comment by MObrien-IDM** [comment]
Data comes from the DHS - use statcompiler if available.

**Comment by AMishra-IDM** [comment]
Most recent Ethiopia DHS that has barrier question is from 2005. Is this recent enough to use?

**Comment by aaslinur** [comment]
Thanks for this update @AMishra-IDM. I see that there is another variable - 12 month contraceptive use discontinuation rates - which was collected in 2005 and 2016. 

year | method failure | desire to become pregnant | other fertility related reasons | side effects, health | wanting a more effecti method | other method related reasons | other reasons | all reasons | switching to another method
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2005 | 2005 | 1.4 | 10.3 | 3.3 | 14.5 | 2.7 | 4.5 | 5.3 | 42 | 12.1
2005
2016 | 0.8 | 10.8 | 4.7 | 7.4 | 4.2 | 4.8 | 2.8 | 35.3 | 5.8

@MObrien-IDM - should the denominator here be women who have ever used contraception or is this broadly related to intentions among all users?

**Comment by AMishra-IDM** [comment]
From team discussion, decided to use the 2005 DHS CP barrier data as a placeholder, as this parameter is not currently used in the model.

**Comment by aaslinur** [comment]
Issue Closed: PR #156
