### ISSUE TITLE
Plotting in sim.py doesn't allow user defined result plots

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#104]
Documentation for arg on sim.plot() seems to say we can input any dictionary of a result:label pair, but it appears we have to use a pre-defined dictionary.

Documentation:
to_plot   (str/dict): What to plot (e.g. 'default' or 'cpr'), or a dictionary of result:label pairs

Attempted usage:
sim.plot(to_plot = {'cpr':  'CPR (contraceptive prevalence rate)'}, do_save=True, filename='sim_cpr.png', new_fig=True)

Error:
  File "/Users/anniebmgf/Documents/GitHub/fpsim/fpsim/sim.py", line 1641, in plot
    raise ValueError(errormsg)
ValueError: Your to_plot value: {'cpr': 'CPR (contraceptive prevalence rate)'} is not a valid option

**Comment by MObrien-IDM** [comment]
@cliffckerr  Could you look into this, please?
