### ISSUE TITLE
Create age of agents with short interval as an agent state

### ISSUE THREAD

**Issue by nnoori-IDM** [fpsim/fpsim#105]
We want to track the birth spacing and the age of each agent at second order and higher live births in FPsim. 
First step:

- [ ] Create short_interval_age as an agent state in sim.py 
https://github.com/fpsim/fpsim/pull/107/commits/57662ec344de503d91b162ab88c7eca238a0e71a

**Comment by MObrien-IDM** [comment]
Let's close out the age-specific short interval issues for now, they **have** been resolved but may resurface if needed as we refactor the age specific tracking code. @nnoori-IDM @avictorious

**Comment by MObrien-IDM** [comment]
Closed with PR #107
