### ISSUE TITLE
keep track of age of agents at birth for short birth intervals at each time step & calculate cumulative number of short birth intervals over year

### ISSUE THREAD

**Issue by nnoori-IDM** [fpsim/fpsim#108]
1. Include only live births
2. Include agents with more than 1 array of birth 
3. calculate the birth spacing and whether it is less than the short birth interval threshold (short_int (issue [106](https://github.com/fpsim/fpsim/issues/106)))
4. Create a list of ages at live birth with birth spacing < short_int 
5. Save into agent state (issue [105](https://github.com/fpsim/fpsim/issues/105))

https://github.com/fpsim/fpsim/commit/c3ee97bf445e264a419e8482de332ea9e7cb7334

**Comment by MObrien-IDM** [comment]
@avictorious @nnoori-IDM Closing this with #107
