### ISSUE TITLE
Breastfeeding duration distribution mu and beta from DHS - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#11]
For parameterizing agents who are currently breastfeeding for LAM use

- [ ] Add code used to process data into "data processing" folder in "locations"

**Comment by avictorious** [comment]
@MObrien-IDM please take a look and let me know what distribution you want to use (DHS vs PMA).  We need to update parameter and add any code you used to arrive at parameters.

**Comment by MObrien-IDM** [comment]
Okay! So, we need to use the DHS. I found the processing file that I used for Senegal, and generalized it to take any DHS KR recode file and fit a distribution to it.

**Comment by mzimmermann-IDM** [comment]
For reference PMS documentation source: https://www.pmadata.org/media/1243/download?attachment
