### ISSUE TITLE
add age-specific tracking of short interval pregnancy over time

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#110]
We are currently able to track how many short interval pregnancies an agent has had over their life and how many are happening at each time step. This allows for 1) a time series of all short interval pregnancies to be plotted during a sim, and 2) for age-specific short-interval pregnancies at the end of the sim to be output and visualized.   Still some work left to do to complete this part of tracking and plotting. 

The next step is to age-bin at each time step to be able to track how many are happening within each age bin at each time step, to produce age-specific plots over time, like those that exist for stillbirth and CPR within the 'track_as' code structure.

**Comment by MObrien-IDM** [comment]
Is this addressed by the draft PR #107 ? If so, let's link it so that it closes when we merge in that PR.

**Comment by avictorious** [comment]
@MObrien-IDM We ended up not putting it within the track_as code structure, but have a parameter where we can track all the short interval births that are happening between certain ages for plotting. This is a parameter within the location file.  It was much simpler to do it this way, and we can look at percent of short-interval births over a time series between any age (15-20, 15-25, 15-30, etc), by adjusting the max and min. 

If that's an acceptable solution to you, we can close with this PR.

**Comment by MObrien-IDM** [comment]
Let's close for now, with the caveat that it may resurface if needed with the age-tracking refactor. Closes with PR #107
