### ISSUE TITLE
revisit birth spacing preferences free parameter and use optimization algorithm

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#115]
Go back to Senegal branch to recalibrate birth spacing preferences in an algorithmic way.  These were fit using manual calibration previously.  If reporting as a data insight, want more robustness behind the values.  Note that values still won't have particular mathematical meaning but overall trend may. 

Plan to use procedure for calibrating birth spacing preference values for Kenya and other contexts

**Comment by MObrien-IDM** [comment]
Has this been closed by PR #119 ?

**Comment by avictorious** [comment]
@MObrien-IDM Yes, I'll close this now
