### ISSUE TITLE
Probability of meeting criteria for LAM by month postpartum - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#12]
Find array of percent of breastfeeding women by month postpartum 0-11 months who met criteria for LAM using DHS calendar data:
1.  Exclusively breastfeeding (breastfeeding and water alone)
2. Menses have not returned

Third criteria for LAM is to be within 6 months postpartum, this is selected for in the algorithm.  Nice to have 0-11 months because it can help in calibration as there is a gradual return to fertility in the postpartum months (important as a fertility parameter in FPsim) despite not meeting strict criteria for LAM as a clinically reliable contraceptive method after 6 months.  

- [ ] Add code used to process data into "data processing" folder in "locations"

**Comment by mzimmermann-IDM** [comment]
Calculated these probabilities (separate and combined shown) from DHS 2014.

[LAM.results_2022-12-08.csv](https://github.com/fpsim/fpsim/files/10190947/LAM.results_2022-12-08.csv)



![Image](https://user-images.githubusercontent.com/48844053/206599622-9f27208c-8f5c-4325-b752-501766c9bb49.png)

**Comment by avictorious** [comment]
@mzimmermann-IDM @MObrien-IDM  very cool!  I just wanted to clarify that this is % of breastfeeding women, not just % of all women.  Because we parameterize breastfeeding as a separate agent state (with Michelle's distribution), only breastfeeding women are fed into this likelihood, so the y axis should be percent of breastfeeding women and then selected for who is "exclusively breastfeeding" and "menses not returned."

I'm not sure how easy it is to separate breastfeeding women from exclusively breastfeeding in DHS, or how much overlap there is between those two populations.

**Comment by mzimmermann-IDM** [comment]
Oh shoot no I forgot this, sorry! Redid with the denominator as the number who reported giving breastmilk. Looks a little higher. 


![Image](https://user-images.githubusercontent.com/48844053/206777459-bd023375-e4f0-42fb-8ff9-72f503225507.png)



[LAM.results_2022-12-09.csv](https://github.com/fpsim/fpsim/files/10197387/LAM.results_2022-12-09.csv)

**Comment by mzimmermann-IDM** [comment]
Another fix, sorry! Realized I forgot to apply population weights. Here's weighted (so nationally representative)
 

![Image](https://user-images.githubusercontent.com/48844053/206808262-23976dfd-bc1e-4958-ab6b-2028f7d1de13.png)



[LAM.results_2022-12-09v2.csv](https://github.com/fpsim/fpsim/files/10198609/LAM.results_2022-12-09v2.csv)

**Comment by avictorious** [comment]
Thanks so much for these @mzimmermann-IDM!  I was looking through for published results on these postpartum and breastfeeding parameters and Kenya (@MObrien-IDM)  and noticed Kenya is talked about as a bit of a success story with exclusive breastfeeding, going from **32% at 6 months in the 2008 DHS** to **61% in the 2014 DHS**: https://internationalbreastfeedingjournal.biomedcentral.com/articles/10.1186/s13006-020-00260-5#:~:text=Exclusive%20breastfeeding%20up%20to%206,cultural%20and%20socio%2Deconomic%20factors. (Look at 2nd paragraph of background) 

The numbers here are a bit lower, 49% exclusive breastfeeding at 6 months in your first analysis (we call it 5 months because month zero is the first month) and 45% weighted and with just breastfeeding women in the denominator. 

Probably just small differences in how it's being tabulated, but wanted to document here nonetheless, and note the significant behavior change for Kenya.

**Comment by avictorious** [comment]
Adding weighted LAM rates into kenya.py
