### ISSUE TITLE
Visible Deprecation Warning message 

### ISSUE THREAD

**Issue by nnoori-IDM** [fpsim/fpsim#124]
After adding the [short birth interval feature](https://github.com/fpsim/fpsim/pull/107) to sim.py, and running some scenario-based simulations, the following warning message pops up, when the "track_as" option in senegal.py is on. 

_sim.py:1480: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.   self.results[key] = np.array(arr) # Convert any lists to arrays_ 

The code runs fine and the age-specific outcomes (as_mcpr, as_imr,etc.) can be plotted. 

With putting track_as back to 0, the message disappears.

**Comment by MObrien-IDM** [comment]
For now, I'm changing the default of track_as in senegal.py to 0  - this should be the default going forward, for all PRs.

**Comment by MObrien-IDM** [comment]
Closed with PR #128 but further refactoring now underway.
