### ISSUE TITLE
Make tutorial scenarios simpler

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#139]
T3 is currently running 7.2 million person-years, which seems excessive. Consider reducing:
- [ ] Repeats (from 3 to 2 or even 1)
- [ ] Number of scenarios (from 6 to 2 or at most 3)
- [ ] Population size (from 10,000 to 1000 or 2000)
- [ ] Number of years (from 40 to 20)

If all of these changes are made, the scenarios should run ~100x faster -- so back to seconds instead of minutes.

**Comment by MObrien-IDM** [comment]
@pausz - Could you tackle this in parallel with the other work on the tutorials you're doing for v2.0?

**Comment by cliffckerr** [comment]
Long since fixed
