### ISSUE TITLE
Consider Binder alternatives

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#141]
Lots of alternatives these days, maybe one of them is better than Binder?
https://sid-sharma1990.medium.com/10-alternatives-for-cloud-based-jupyter-notebook-d6201af1126e

**Comment by MObrien-IDM** [comment]
I'd support moving the tutorials to Google Colab - we had to do this temporarily for the ABM workshop.

**Comment by cliffckerr** [comment]
Since the FPsim repo is public, they're already available on Colab; we just need to update the link as we have for Starsim, e.g.:
https://docs.idmod.org/projects/starsim/en/latest/tutorials/tut_intro.html

**Comment by cliffckerr** [comment]
Closed by #445
