### ISSUE TITLE
Only allow sexually active agents to enter the contraceptive matrix

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#145]
- Set guardrails so that intervention scenarios are targeting only sexually active women
- Consider applying to sexual debut so only women who have debuted may enter the matrix
- Need to solve for fact that contraceptive use probabilities come from all women annually
- Compare current version vs new version to see how much affect this has on overall model outcomes

**Comment by MObrien-IDM** [comment]
Thanks, @avictorious 
Just to add - we want the entry to still be probabilistic, so whether we use infrequent sex (my preference) or sexual debut, or a combination, we want infrequent or non-debut-ers to still have a nonzero probability of entering the matrix (albeit very very small) 

Also, @mzimmermann-IDM  Should have the contraceptive matrices re-done for women who've had sex in the last 12 months. Might make sense to co-create with her!

Let me know how I can support.

**Comment by mzimmermann-IDM** [comment]
Yes I do! Happy to share when you have a branch for this.

**Comment by MObrien-IDM** [comment]
Closed with PR #157
