### ISSUE TITLE
Parity-specific contraceptive use - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#15]
Find estimate of what parity level CPR starts to increase in the population, used to make it more likely that agents will take up contraceptives at a parity breakpoint

Parameter is "parity" and "high_parity_nonuse" can be used in calibration

- [x] Add code used to process data into "data processing" folder in "locations"

**Comment by avictorious** [comment]
Visualized mCPR by parity in Kenya 2014 DHS (latest year available).
Difference from Senegal:  Higher contraceptive use in nulliparous women (7.7% vs 1.3%).  Parity pattern otherwise similar, high use in parity 3 and 4



  | v201 | v313 | Percent
-- | -- | -- | --
Parity|Modern|Percent
0.0 | 3 | 7.732788
1.0 | 3 | 42.848299
2.0 | 3 | 55.273409
3.0 | 3 | 57.852376
4.0 | 3 | 55.487674
5.0 | 3 | 51.818004
6.0 | 3 | 46.339312
7.0 | 3 | 35.956647



![senegal_mcpr_parity](https://user-images.githubusercontent.com/65202227/202022113-224d6935-e68b-4364-bf1b-b33c222bc435.png
![kenya_mcpr_parity](https://user-images.githubusercontent.com/65202227/202022121-88e7269f-6486-4369-9c70-e192f499afd7.png)
)

**Comment by avictorious** [comment]
Code for analyzing and visualizing mCPR by parity for DHS file added as 'mcpr_by_parity.py"

**Comment by MObrien-IDM** [comment]
No longer applicable - not enough data for this particular method, but other changes helping to incorporate parity.
