### ISSUE TITLE
Implement initialisation strategies for new attributes. 

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#172]
If a location/context is not specified (ie, country) in a simulation, what would be the defaults for:
- [x] `paid_employment` #185 
- [x] `partnered` #186 
- [x] `control_over_wages` #187 
- [x] `sexual_autonomy` #188 
- [x] `urban` #189 
- [x] `education_attainment` #190

For instance, for age and sex ratio fpsim uses a default age pyramid from a specific location and a specific year. What would be the equivalent default source data for the other attributes?

**Comment by mzimmermann-IDM** [comment]
We will use country specific data for the new inputs from Kenya DHS. I'll make an issue to list all of the data points we need and I can pull them.

**Comment by mzimmermann-IDM** [comment]
I'm thinking about how is best to do this for the parameters that are dynamic like the work and decision making metrics. These will change over time via a function, but that leaves the question of how to initialize. Do we just pick an age (say age 15) and use the population distribution at that age? That would be easy but I'm afraid our function won't have enough power to account for changes over the whole lifetime. Let me brainstorm with @MObrien-IDM .

**Comment by pausz** [comment]
Empowerment data covers the range 15<= age < 50. There remains the question on how to initialise this metric for women aged < 15 and >=50. 


Current implementation:
- for women aged < 15: assign half the value of metric for women aged 15<= age <16.
- for women aged >=50: assign the same value of the metric as for women aged 40<= age <50.
