### ISSUE TITLE
Pull metrics from DHS data for empowerment work

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#175]
We need several new data points for the empowerment enhancements. I will pull them from the most recent Kenya DHS. These will include:

- [x] Percentage of women with each number of years of education by age and parity
- [x] Probability of doing paid work by age
- [x] Average decision making power over wages by age
- [x] Average ability to refuse sex by age
- [x] urban/rural percentages
- [x] age distribution of partnership formation

From our PMA analysis, we will need the parameters from the functions for change in the three empowerment metrics annually. These will include coefficients from the functions:
- [x] contraceptive use by age, parity, postpartum, work, control over wages, ability to refuse sex, partnership, education, and urban/rural
- [x] work by age, parity, partnership, education, and urban/rural
- [x] control over wages by age, parity, partnership, education, and urban/rural
- [x] ability to refuse sex by age, parity, partnership, education, and urban/rural

**Comment by pausz** [comment]
@mzimmermann-IDM: While refactoring the loading of `education.csv` (from  pandas multiindex dataframe to ndarray) I noticed the following: 

```
 data["edu"].unique()
array([24, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1,  0])

```
There's no data for "22" and "23" education years. Is this expected?

![image](https://github.com/fpsim/fpsim/assets/1563810/4044e7b8-b3cc-4fad-ba47-ef5e0d9bf977)

**Comment by mzimmermann-IDM** [comment]
Definitely not! I realized I calculated these wrong, and am still trying to figure out how to do it. I will let you know when I have a better version.
