### ISSUE TITLE
Implement empowerment functions

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#176]
Empowerment metrics (work, decision making autonomy over wages, ability to refuse sex, decision making over health) change each year as a function of age, parity, education, contraceptive use, urban/rural . After all of these parameters are initialized we need to create the functions.

The numbers will change as this is not final, but the function will look something like this (this is for paid work, but I'll make for all of them):
age -0.00117
contraception  0.513711
intercept  0.140257
number of births 0.019958
paid work previous year 0.040991
years of school 0.025155
urban 0.02092

**Comment by mzimmermann-IDM** [comment]
I created the first version of the models for these, and put the output in a csv here: https://github.com/fpsim/fpsim/blob/Empowerment_functions/fpsim/locations/kenya/empower_coef.csv

In this file are the coefficients results from models that predict each of the 4 empowerment variables we now have in the model. A few notes:
- separate models for each of the 4 empowerment metrics (the 'metric' variable tells you which model results you are looking at).
- lhs is what you are predicting, so basically the things we are interested in are the 4 metrics.
- rhs is the predictor. anything with a _0 means it's from the year prior.
- For the op column, ~1 is an intercept, ~ is the effect, and ~~ is the covariance. I'm not sure yet how to use the covariances, but I think we need to include to get the uncertainty right. This is a to do to figure out for me.
- current_contra is the probability of currently using and contraceptive method, and live_births are the total number of births... the rest of the variables I think are named consistently with the model, but let me know if you want me to change any (can change contra and births too).

These models will certainly change, but this should give enough structure to start writing code for it when you have the time.

To do for me:
- Figure out how to implement covariances
- Education is coded wrong in the data, need to fix
- Try using spline with age
- Validation of model structure

cc @robynstuart @MObrien-IDM

**Comment by mzimmermann-IDM** [comment]
Ok, functions are corrected. I simplified the analysis so they are just logistic regression functions, which are hopefully straightforward to implement. You will see the four lhs variables and the rhs covariates. The _0 means it's the value from the prior year. Still two to do items for me, recode education and add a spline for age. Note that for sexual autonomy, there was no change over time, so previous value is 100% predictive.

https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/empower_coef.csv

@robynstuart , is this clear now? If so, I can do a PR so you can use this file directly.

**Comment by robynstuart** [comment]
@mzimmermann-IDM just checking, the function for sexual autonomy looks like we're just keeping that constant over time - is that right?

**Comment by mzimmermann-IDM** [comment]
@robynstuart Yeah, in the data no one changed over time, so I guess that's what we are doing!

**Comment by robynstuart** [comment]
Implemented on the https://github.com/fpsim/fpsim/tree/methodtime/fpsim branch
