### ISSUE TITLE
Add empowerment metrics to calibration targets

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#177]
We want to be able to calibrate to paid work, control over wages, and ability to refuse sex.

**Comment by emilydriano** [comment]
@mzimmermann-IDM how do we want to calculate the model results of each of these metrics after a sim? (i.e. median, avg per individual age, age buckets, etc)?

**Comment by mzimmermann-IDM** [comment]
Great question. I think mean by age would be great. We could simplify to age bins if that makes it easier.

**Comment by emilydriano** [comment]
Sounds good! Starting with mean by age. If it significantly affects performance, we can switch gears to age bins.

**Comment by emilydriano** [comment]
@mzimmermann-IDM I finished adding the ability to calibrate to paid_work, so I'm working on adding education as a calibration target & I have a few clarifying questions. With respect to the data to which we want to calibrate the model, would we be using edu_initialization.csv (with number years edu per age) as our target? And then use the model param 'edu_attainment' to compare to this? In theory we could also compare the edu_objective in data vs model, but not sure if the educational attainment is a variable you care more about in calibration.

**Comment by MObrien-IDM** [comment]
@emilydriano @mzimmermann-IDM -- Is this resolved? :)

**Comment by emilydriano** [comment]
@MObrien-IDM this will be resolved with PR #240 which is ready to merge once you and @mzimmermann-IDM have reviewed.
