### ISSUE TITLE
Attaching issues to a project is broken 

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#18]
When creating a project board, issues are not able to be assigned to a new project without causing the error below.

<img width="1647" alt="Screen Shot 2022-11-11 at 11 39 40 AM" src="https://user-images.githubusercontent.com/65202227/201761311-44c66657-529d-43d3-8cde-9da44301617a.png">

**Comment by cliffckerr** [comment]
This has been long since fixed!
