### ISSUE TITLE
Implement intialisation strategy for `paid_employment`

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#185]
Current implementation for `paid_employment`:
- for women aged < 15: assign probability 0
- for women aged >=50: assign probability 0 which seems unrealistic.

**Comment by pausz** [comment]
Update: @mzimmermann-IDM  will look into extrapolating values  in the input datasets

**Comment by mzimmermann-IDM** [comment]
I put the inflection point for this one at age 25. It does look like there's more of a peak from age 35-45, so maybe this is too simplified. But we don't necessarily need all the detail.
![image](https://github.com/fpsim/fpsim/assets/48844053/fdd6aa39-d58a-4220-a7b3-2ebcd5ac6867)

Parameterization:
0.6198487 at age 25
slope <25, 6.216042e-02 (SE 2.062729e-03)
slope >25, 0.0008010242 (SE 0.0592966648)

**Comment by pausz** [comment]
@mzimmermann-IDM Once I implemented the piecewise linear parameterisation, I noticed that for ages < 15 we would get negative proportions/probabilities. To overcome this I've implemented an asymmetric logistic function. Data, linear and logistic fits are shown below: 

![image](https://github.com/fpsim/fpsim/assets/1563810/a8381f9c-a4b1-459f-b02a-7917affdafd8)

The fitting process is done right after loading empowerment data , so in principle we can change the function that we fit to data. We wouldn't have to change the parameterisation if the data source changes either (eg, we use a dataset from a different year).  
 
Let me know if you think of any potential issues we may have with this approach. 


** I noticed that the logistic fit in the figure doesn't reach to 0 for ages < 5 years old -- it's very small approx 0.04. I'll look into that next.

**Comment by pausz** [comment]
Paid employment with more segments to the piecewiselinear parameterisation:

![image](https://github.com/fpsim/fpsim/assets/1563810/f1e9752e-40d0-4eab-beca-d93808510855)

Choice of additional inflection points and slopes are in [`kenya.py`](https://github.com/fpsim/fpsim/commit/28b7c00d82ea155f7ef36da1e9806e181000b799)
