### ISSUE TITLE
Implement initialisation strategy for `control_over_wages`

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#187]
Current implementation for `control_over_wages`:
- for women aged < 15: assign half the value of metric for women aged 15<= age <16.
- for women aged >=50: assign the same value of the metric as for women aged 49<= age <50.

**Comment by pausz** [comment]
Update: @mzimmermann-IDM  will look into extrapolating values  in the input datasets

**Comment by mzimmermann-IDM** [comment]
I put the inflection point here at age 20. It looks fine, though we could probably just use an average over age 20 if we want to simplify. It looks pretty flat to me.
![image](https://github.com/fpsim/fpsim/assets/48844053/b07d138a-d1c2-4f9b-9704-d9eeb2b56fe5)

Parameterization:
0.9434381 at age 20
slope <20, 2.548961e-02 (SE 5.243655e-03)
slope >20, 0.0008366125 (SE 0.0194093421)

**Comment by pausz** [comment]
Not sure what happened here, but the decision making/control over wages data points (blue) I load from [empowerment.csv / column=`decisionwages`](https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/empowerment.csv) don't look like the ones in the figure above. The values in my figure look overall lower. 

![image](https://github.com/fpsim/fpsim/assets/1563810/2af9c57d-9244-42ab-8b9e-5f66a604d8c3)
