### ISSUE TITLE
Implement intialisation strategy for `sexual_autonomy`

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#188]
Current implementation for `sexual_autonomy`:
- for women aged < 15: assign half the value of metric for women aged 15<= age <16.
- for women aged >=50: assign the same value of the metric as for women aged 49<= age <50.

**Comment by pausz** [comment]
Update: @mzimmermann-IDM  will look into extrapolating values  in the input datasets

**Comment by mzimmermann-IDM** [comment]
How does this look? I put the inflection point at age 25, and just did a linear regression on each side. I picked 25 just visually, but it also seems like a reasonable age to choose. We could also use a more complex function to get a better fit, but I think this looks decent.
![image](https://github.com/fpsim/fpsim/assets/48844053/1c0f8fc2-458b-4584-9bd3-de90b4e416aa)

Parameterization:
0.8292142 at age 25
slope <25, 0.025677  (SE 0.003474)
slope>25, -0.003916498 (SE 0.026119389)

**Comment by pausz** [comment]
Piecewise linear approximation over the range 0 to 100 years:
![image](https://github.com/fpsim/fpsim/assets/1563810/0c5b09c5-adad-41d7-b96d-51a5a81c3f4f)
