### ISSUE TITLE
Replace skyscraper plots with user-friendly heatmaps

### ISSUE THREAD

**Issue by MObrien-IDM** [fpsim/fpsim#198]
Based on a series of conversations in July, we would like to replace the skyscraper plots, which are difficult to interpret, with heatmaps of the distribution of the FPsim agent population over age and parity. 

Initially, we discussed normalizing the heatmaps so that they show more variation and are slightly easier to interpret. They need robust labelling so that users (without IDM assistance) can interpret as they calibrate. 

@cliffckerr Assigning this to you since you'd started to work on some alternatives :) If you want to recruit anyone to help, please feel free.

**Comment by emilydriano** [comment]
resolved with PR #202
