### ISSUE TITLE
Implement new empowerment attribute `dv_acceptability`

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#208]
- [ ] add new attribute to people and add its default
- [ ] add data to kenya.py 
- [ ] add functions to ingest & preprocess data
- [ ] initialise attribute
- [ ] record attribute
- [ ] visualise attribute

**Comment by mzimmermann-IDM** [comment]
PMA does not collect sufficient data on this to allow for inclusion in the model. At this time, we won't include it.
