### ISSUE TITLE
New empowerment metric: decision making autonomy over health 

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#211]
I'd like to implement one more empowerment metric, control over health decisions. Should be implemented similarly to the others. I added this to the empowerment csv for Kenya.  It looks like this:
![image](https://github.com/fpsim/fpsim/assets/48844053/0bc43b5b-10a0-4639-9bf4-220531c2dcee)
It's all pretty close to 1, s maybe we just use this directly and assume 1 for older/younger. Thoughts?

**Comment by pausz** [comment]
@mzimmermann-IDM How does this interpolation looks? The green line "corrected data" uses the following parametrisation: inflection_age, inflection_prob, m1, m2 = (16.0, 9.90297066e-01, 6.26846208e-02,  1.44754082e-04), and also guarantees that there are not values below 0 and above 1.  

![image](https://github.com/fpsim/fpsim/assets/1563810/b37017a5-8a32-41d0-8125-557282266301)

**Comment by mzimmermann-IDM** [comment]
This looks great @pausz ! Thank you.

**Comment by mzimmermann-IDM** [comment]
When you have a chance, could you add all of these parameterizations to the methods doc you made, so we can remember what they all are? Thank you!
