### ISSUE TITLE
Use standard error from data to initialise empowerment metrics

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#212]
There's one main challenge to use the SE for each empowerment metric: how to pass a random seed during parameter creation. A random seed is defined in`kenya.py/scalar_pars()`, and we can potentially pass this seed to `kenya.py/empowerment_distributions()`. 

Once we solve this step, the next change that needs to happen is replacing the current linear interpolation parametrisations by an optimisation step that estimates the interpolation parameters.

**Comment by pausz** [comment]
Automated linear interpolation/extrapolation of empowerment metrics, using mean and SE values
![image](https://github.com/fpsim/fpsim/assets/1563810/455103b9-8b01-4ae9-99a3-31256395d7d8)

**Comment by pausz** [comment]
@mzimmermann-IDM I want to confirm with you:
Do the columns ending in .se (e.g., paid_employment.se) represent the standard error of the mean for a specific age group, or do they represent the standard deviation of the metric for the population at a specific age?

**Comment by mzimmermann-IDM** [comment]
SE of the mean for a specific age group. Thanks for checking!
