### ISSUE TITLE
Run sim.results - Subnational

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#238]

**Comment by emilydriano** [comment]
Attached are sim results and plots from a run with 100,000 agents using the free params from the Ethiopia national model. 
[ethiopia_region_results.csv](https://github.com/fpsim/fpsim/files/14030790/ethiopia_region_results.csv)
![fpsim](https://github.com/fpsim/fpsim/assets/108016846/8323d9fc-6ede-45e3-b61e-8932a679cb57)

**Comment by aaslinur** [comment]
Issue Closed: PR https://github.com/fpsim/fpsim/pull/241
