### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#248]
Can you update the theme_overrides.css file to use one of the blues specified in our logo usage guide for link text? https://bmgf.sharepoint.com/sites/IDMOD/Shared%20Documents/Forms/AllItems.aspx?noAuthRedirect=1&id=%2Fsites%2FIDMOD%2FShared%20Documents%2FTemplates%20and%20Logos%2FIDM%20Logo%2FIDM%20Logo%20Usage%20Guide%2Epdf&viewid=acb933e7%2D35e7%2D459d%2Dba31%2D1c1bff1595fb&parent=%2Fsites%2FIDMOD%2FShared%20Documents%2FTemplates%20and%20Logos%2FIDM%20Logo

_Originally posted by @JSchripsema-IDM in https://github.com/fpsim/fpsim/pull/247#pullrequestreview-1866057823_
            

See https://pydata-sphinx-theme.readthedocs.io/en/v0.9.0/user_guide/customizing.html

Need to update 0073A3 to 0A7D91

**Comment by MObrien-IDM** [comment]
Is this still an issue, @cliffckerr @JSchripsema-IDM

**Comment by JSchripsema-IDM** [comment]
Yes, they are still using a grayish blue.

**Comment by cliffckerr** [comment]
I think this is OK? The links are using `#0A7D91`:
![image](https://github.com/user-attachments/assets/caaac84a-8c40-483a-b234-1d9bc458f391)

And they seem to match e.g. the EMOD-API docs:
https://docs.idmod.org/projects/emod-api/en/latest/index.html

**Comment by cliffckerr** [comment]
Going to close for now, but we can reopen if needed.
