### ISSUE TITLE
Sexual activity of postpartum women - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#25]
Use DHS data to find an array of probabilities that women have resumed sexual activity by month postpartum.  Uses months since last birth and sexual activity within the last 30 days.

**Comment by avictorious** [comment]
On further discussion, we were previously using percent of women reporting abstaining from sex in the postpartum period, and now are using a cross tab of months postpartum and reporting sex within the last 4 weeks. 

This change (done over a year ago) resulted in fairly high percentages of women having sex within the first 3 months postpartum.  We then corrected this with a birth spacing preference free parameter reducing the likelihood of having sex in the first 9 months by half. 

Will have a discussion with Michelle and Marita and document the plan for this data source here.

**Comment by mzimmermann-IDM** [comment]
Upon discussion with @avictorious and @MObrien-IDM , we decided to calculate using both methods. We could use as low and high bounds or use something between. Attached are the two values, where method 1 is using duration of postpartum abstinence with months pp, and method 2 is using sexually active in last 4 weeks with months pp. Not that method two overlooks if someone was sexually active pp, then stopped having sex in the last month. Below are what the two curves look like. Regardless of which we use, we might want to smooth them?

[sexually.active.results_2022-12-08.csv](https://github.com/fpsim/fpsim/files/10190936/sexually.active.results_2022-12-08.csv)



![Image](https://user-images.githubusercontent.com/48844053/206599141-282da54b-79bd-4388-af83-3be9f1de7062.png)

**Comment by avictorious** [comment]
@mzimmermann-IDM @MObrien-IDM  This is super interesting.  I wonder if there's something about the way the data is coded that has a tendency to overestimate sexual activity within the first 1-2 months postpartum when using method 2?  It seems like postpartum abstinence captures that behavior a bit better (very few active women in the first 6 weeks like you might expect).  Past the first few months postpartum, it does seem like method 2 does a better job at approximating the fraction of exposed women each month, which is what we're after.  

This brings up again the idea of how we're uniformly applying sexual activity across agents -- when in reality, just like around sexual debut, the likelihoods are less uniform.  Some women take a long time to return to sexual activity, even 2-3 years.  These may be women who had a challenging delivery and recovery, or any number of biological or social reasons why they don't return to activity for some time.  

So, I think they're both right -- some small fraction of women remain abstinent even to 24 months, though most return to some activity within 6-12 months postpartum.  And, on average ~60% of women return to at least monthly sexual activity between 6-12 months.  For FPsim, it seems like we want to capture that "time to debut" in the first few months and then the likelihood of monthly exposure after that.

**Comment by mzimmermann-IDM** [comment]
I was wondering that too, but I can't tell anything obvious. Could just be noise? The sample sizes are not that big. There is a bunch of missing data, but it's for both methods, not specific to the second. Method 2 does make more sense once it's not postpartum, so we might have to decide when to switch.

One other option (since we need to throw another in the mix haha) would be to use the question about how many months after birth were you abstinent (for women who have started having sex again). It would be a change, but we could assign a length of abstinence time based on this distribution.



![Image](https://user-images.githubusercontent.com/48844053/206771582-f779c899-dbf8-4f72-bfe6-2a168813ba9e.png)

**Comment by MObrien-IDM** [comment]
The only problem with that retrospective question, @mzimmermann-IDM is the tendency to round it out - hence the spike at 12 months. 

Method 1 and method 2 are estimating different aspects of postpartum abstinence, right? Method 1 would be a retrospective accounting of how many months postpartum the woman abstained from sex (cumulative), while Method 2 would give have you been sexually active in the last four weeks, given you are X months postpartum (monthly). So, I'm not sure we can compare them directly to conceptualize the same dynamic. 

@avictorious I think you're right that this does give me the sense that we had when we built in sexual debut. It's possible that what we are failing to capture here is the individual-level pattern of being more likely to do what you've been doing than to do something new altogether (sexual inertia?) 

What I think we were attempting to do with the hybrid approach originally was capture the time to debut, followed by the frequency. We may need to consider this for postpartum sex as well. Time to return + once you've returned the monthly probs.

**Comment by mzimmermann-IDM** [comment]
Yes, agreed with both of your points @MObrien-IDM . Could just use a distribution for up to 11 months? Then combine everything over a year for a single probability?

Also forgot to weight these, so here's the weighted.



![Image](https://user-images.githubusercontent.com/48844053/206808504-eea93990-de1a-4ca2-be40-a2cac8f0234d.png)



[sexually.active.results_2022-12-09.csv](https://github.com/fpsim/fpsim/files/10198617/sexually.active.results_2022-12-09.csv)

**Comment by MObrien-IDM** [comment]
@mzimmermann-IDM @avictorious That's a really good idea, Annie. Maybe it's a fool's errand to try to parameterize postpartum sexual activity so far out. Maybe we just take a look at the first six months? And then agents all return to their age-specific sexual activity estimates.

**Comment by avictorious** [comment]
Added weighted array using method 2 for now to Kenya calibration draft.
Will use this variable as needed in manual and automatic calibration to see how well we are fitting patters and adjust as needed.
