### ISSUE TITLE
Contraceptive choice parameter initialization

### ISSUE THREAD

**Issue by robynstuart** [fpsim/fpsim#266]
Currently reading these in from a csv file, but how would this generalize? Or will users have to create the csv files themselves? If so, we will need steps to follow

**Comment by mzimmermann-IDM** [comment]
I think we can continue to read in from CSV, but I will add the R code for how I generated it for reference. Do you have any other suggestions @robynstuart or @MObrien-IDM ?

**Comment by robynstuart** [comment]
Implemented on the https://github.com/fpsim/fpsim/tree/methodtime/fpsim branch
