### ISSUE TITLE
Functions to update empowerment metrics

### ISSUE THREAD

**Issue by robynstuart** [fpsim/fpsim#267]
paid_employment, decision_wages, decision_health, sexual autonomy all need to be dynamically updated. What functions are being used to update these?

**Comment by mzimmermann-IDM** [comment]
Is this the same as issue #176 ? Function parameters are here. I still need to add the R code for how I generated these. I will do a PR for all of the function generation R code.
https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/empower_coef.csv

**Comment by robynstuart** [comment]
yep, same as #176
