### ISSUE TITLE
Decide whether to support multiple types of method selection

### ISSUE THREAD

**Issue by robynstuart** [fpsim/fpsim#268]
Will we continue to support contraceptive matrices or will these be deprecated?

**Comment by mzimmermann-IDM** [comment]
My vote is to depreciate them and only support one method.

**Comment by robynstuart** [comment]
I'd like to support multiple if possible - I've implemented it this way for now, will await feedback

**Comment by MObrien-IDM** [comment]
@robynstuart  Do you mean that users would choose between a time on method and the original matrices?

**Comment by robynstuart** [comment]
I think we can support:
- fully parameterized contraceptive update functions that assign each woman a time on method that depends on various other variables
- functions that automatically update a woman's contraceptive choice each year

From an implementation standpoint, these two are not very different. Users can specify their own 'update' functions, so if they want to pass in a function that emulates the contraceptive transition matrices then technically this would be possible.

**Comment by robynstuart** [comment]
Implemented on the https://github.com/fpsim/fpsim/tree/methodtime/fpsim branch
