### ISSUE TITLE
Inf values in afb.table.csv's 

### ISSUE THREAD

**Issue by emilydriano** [fpsim/fpsim#309]
The script locations/data_processing/age_at_first_birth_DHS.R generates afb.table.csv files for different countries, and these files contain multiple instances of the value 'Inf' in the "afb" column (see attached). This causes the Inf values to be included in the data percentiles for afb in the Experiment class, affecting the baseline values referenced in [this ](https://github.com/fpsim/fpsim/issues/303)issue.

<img width="112" alt="Capture" src="https://github.com/fpsim/fpsim/assets/108016846/2905f769-ec9e-49b2-9e7c-00fecee8c9ea">

**Comment by MObrien-IDM** [comment]
Resolved with #264
