### ISSUE TITLE
Contraceptive method switching matrices, annual - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#32]
Use PMA data to create matrices that track the likelihood of initiation, continuing, switching, or discontinuing methods each year by age group

- [x] Add code used to process data into "data processing" folder in "locations"

**Comment by mzimmermann-IDM** [comment]
Matrices are done. Code is here: https://github.com/InstituteforDiseaseModeling/FP-DHS/blob/master/Switching_matrices/Switching%20calendar%20analysis%20PMA.R

Matrices are attached and here: https://github.com/InstituteforDiseaseModeling/FP-DHS/blob/master/Switching_matrices/Results/matrices_Kenya_PMA_2022-11-30.csv
[matrices_Kenya_PMA_2022-11-30.csv](https://github.com/fpsim/fpsim/files/10128198/matrices_Kenya_PMA_2022-11-30.csv)
 
Take a look and make sure they have everything you need!

**Comment by avictorious** [comment]
@mzimmermann-IDM Thanks for these!  It looks like these were written to produce the overall initiation probability of starting any method and then the switching probabilities including discontinuation in a separate matrix?  I think we talked about this as a strategy last year but to my knowledge we're still using the traditional matrices?  Let's look at these today and chat.

**Comment by mzimmermann-IDM** [comment]
Updated matrices to be the old format (initiation included in a single matrix). Also reordered so it should match your code.
[matrices_Kenya_PMA_2022-12-05.csv](https://github.com/fpsim/fpsim/files/10157007/matrices_Kenya_PMA_2022-12-05.csv)

**Comment by mzimmermann-IDM** [comment]
Additionally created a matrix from the 2014 DHS (above is 2019-20 PMA) if you want to compare.
[matrices_Kenya_DHS_2022-12-05.csv](https://github.com/fpsim/fpsim/files/10157181/matrices_Kenya_DHS_2022-12-05.csv)

**Comment by avictorious** [comment]
I added a file to process these to be in the format they are in in the parameters file.
Now able to run fpsim with these matrices in place. 
Below is the before replacing matrices with Kenya data and after.  All three categories of matrices are replaced (annual, 6 month postpartum, and 1 month postpartum). Almost all parameters are updated with exception of postpartum sex likelihood and LAM likelihood

FPsim running with Kenyan data but Senegal matrices

![Image](https://user-images.githubusercontent.com/65202227/206000485-77332785-16f6-45b5-9b51-6ab58e9c3562.png)

FPsim running with Kenya data and Kenyan matrices

![Image](https://user-images.githubusercontent.com/65202227/206000678-a9841099-cb63-46cb-ae45-8b22d603900c.png)
