### ISSUE TITLE
Separate urban from empowerment metrics in data processing scripts

### ISSUE THREAD

**Issue by MObrien-IDM** [fpsim/fpsim#322]
Data processing scripts for empowerment metrics are also the ones that contain urban (e.g. empowerment_urban_partnership_dhs.R) - when people are making urban proportion without running the empowerment module, this is not a very intuitive place to go to see how to build their parameters. It would be great to separate these out. Thank you!

**Comment by pausz** [comment]
@MObrien-IDM I agree.  

I think these script made their way to main, but I believe they were written as as a one off scripts when we first added empowerment/urban. We can definitely tide them to provide users with examples. 

Should we also provide equivalent scripts in Python?
