### ISSUE TITLE
Contraceptive method switching matrices, postpartum first month - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#33]
Use PMA data to create matrices that track the likelihood of initiation, continuing, switching, or discontinuing methods in the first month postpartum by age group

- [x] Add code used to process data into "data processing" folder in "locations"

**Comment by mzimmermann-IDM** [comment]
Done, see comment on issue #32

**Comment by avictorious** [comment]
Done see issues #32
