### ISSUE TITLE
Add fertility intent

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#337]
Add an attribute for fertility intent, defined as wanting a pregnancy within the next year. This is age dependent, and will be assessed each year. I added a data processing file, and csv of the probability of having fertility intent by age here:  https://github.com/fpsim/fpsim/tree/Kenya_empowerment_DHS/fpsim/locations/data_processing

One question for us to discuss (@MObrien-IDM , @robynstuart , @pausz): The survey question actually has a third answer, which is "Says she can't get pregnant". This does tend to be a lot of women, especially at the older age groups. I left them as missing for now, but that doesn't make sense, because the percentages with fertility intention are too high. Another option would be to explicitly add that category, but that didn't quite feel right to me either, because it seemed like an infertility metric, and we already have fecundity. Thoughts? Are we ok with having that as an attribute, or does anyone else have a good idea? I thought of only applying to women with higher fecundability, but that would only work for older ages, and a lot of younger women wouldn't know they can't get pregnant. Would love suggestions!

**Comment by mzimmermann-IDM** [comment]
Yes could be interesting. The only thing we are using it for for now is as a predictor of intent to use contraception. So for that purpose, it probably makes sense to have the third category, because we don't want a whole bunch of post-menopausal women using contraception.

**Comment by mzimmermann-IDM** [comment]
Ok, edited to add a category. (Also found an error so that category isn't actually as big as I thought, but still some).

**Comment by pausz** [comment]
@mzimmermann-IDM I realised I didn't include [`intent_coef.csv`](https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/intent_coef.csv) in the PR. 


Is there a code example of how we intend to use the data in this file in fpsim?  Sorry if I missed this info somewhere -- i have a vague recollection we discussed it in a meeting.

**Comment by pausz** [comment]
There are also some suggestions to rename column names (also affects empower_coef.csv) to something that maps better to variable names inside fpsim. I'd be interested in hearing others opinions and suggestions about this too. 

- "Estimate":  This is the estimated value or predicted value of the metric in "`lhs`" --> maybe just "`estimate`" 
- "Std. Error": Is this standard error (of the mean):? If yes I'd rename it "`sem`" or "`se`" -- the latter form is used in other csv files.
- "t value": Is this the value from a t-distribution? `"t_statistic`" or "`t_test_value`"; or "`t_stat`", "`t_val`" for short-form names. Probably "t_stat" over "t_val" because  variables starting with "t" are generally related to time inside fpsim.   
- "Pr(>|t|)": p-value of a statistical t-test, right? If so, "p_value" or "p_val". 


I'll load each csv files as is, and handle renaming of column names after loading. I can make more permanent changes in the R scripts at a later stage -- mainly because I don't yet have all the DTA files required to regenerate the csv files.

**Comment by mzimmermann-IDM** [comment]
> @mzimmermann-IDM I realised I didn't include [`intent_coef.csv`](https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/intent_coef.csv) in the PR.
> 
> Is there a code example of how we intend to use the data in this file in fpsim? Sorry if I missed this info somewhere -- i have a vague recollection we discussed it in a meeting.

Oh yes! These are the coefficients for the function to determine intent to use contraception (not fertility intent). We put contraceptive intent in already, right? So we will use intent_coef to determine annually yes/no.

**Comment by mzimmermann-IDM** [comment]
> There are also some suggestions to rename column names (also affects empower_coef.csv) to something that maps better to variable names inside fpsim. I'd be interested in hearing others opinions and suggestions about this too.
> 
> * "Estimate":  This is the estimated value or predicted value of the metric in "`lhs`" --> maybe just "`estimate`"
> * "Std. Error": Is this standard error (of the mean):? If yes I'd rename it "`sem`" or "`se`" -- the latter form is used in other csv files.
> * "t value": Is this the value from a t-distribution? `"t_statistic`" or "`t_test_value`"; or "`t_stat`", "`t_val`" for short-form names. Probably "t_stat" over "t_val" because  variables starting with "t" are generally related to time inside fpsim.
> * "Pr(>|t|)": p-value of a statistical t-test, right? If so, "p_value" or "p_val".
> 
> I'll load each csv files as is, and handle renaming of column names after loading. I can make more permanent changes in the R scripts at a later stage -- mainly because I don't yet have all the DTA files required to regenerate the csv files.

I agree with renaming to estimate and se. We aren't even using the other columns, so we could probably just drop them the R code when we produce the csv's.

**Comment by pausz** [comment]
> > @mzimmermann-IDM I realised I didn't include [`intent_coef.csv`](https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/intent_coef.csv) in the PR.
> > Is there a code example of how we intend to use the data in this file in fpsim? Sorry if I missed this info somewhere -- i have a vague recollection we discussed it in a meeting.
> 
> Oh yes! These are the coefficients for the function to determine intent to use contraception (not fertility intent). We put contraceptive intent in already, right? So we will use intent_coef to determine annually yes/no.

Oh ok! Cool, then the PR about fertility intent is complete. 

Re intent to use contraception: I don't know if it's in. Doesn't seem to be in the branches I've been working, but I've been using `main` as my base branch. I'd imagine `intent_to_use` be in one of the branches with all the new work on methods.
