### ISSUE TITLE
New empowerment metrics

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#342]
We need to add new empowerment metrics for:

- Decision making over major purchases (buy_decision_major)
- Decision making over daily household purchases (buy_decision_daily)
- Decision making over clothing purchases (buy_decision_clothes)
- Decision making over partner's wages (decide_spending_partner)
- Have savings (savings)
- Know where to get financial info (financial_info)
- Have financial goals (financial_goals)
- Composite for decision making
- Composite for financial autonomy

For all but the composites, I have added the initial value by age to the CSV (variables names in the parentheses above) here: 
And the code to get these values is here: https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/empowerment.csvhttps://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/data_processing/empowerment_urban_partnership_dhs.R

For the two composite measures, they are calculated based on this article: https://www.tandfonline.com/doi/full/10.1080/13545701.2024.2339979?src=

There is a new CSV of the factor loadings here: https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/CFA.loadings.csv. For the decision autonomy, you multiple the loading value by the value of that variable for the four decision making variables included in the factor csv and sum them. For the financial autonomy, you multiply the factor by the variable for savings, financial knowledge, and financial autonomy and sum those They should be recalculated each year.

**Comment by mzimmermann-IDM** [comment]
Parameters for the annual functions for these are also included in the empower_coef csv now! Except the two composites, which are calculated annually per the composites.

**Comment by pausz** [comment]
Illustrating different draws for each empowerment variable using the mean and se data in empowerment.csv
![image](https://github.com/fpsim/fpsim/assets/1563810/41785aed-7ad2-49a0-a608-833bba464917)

**Comment by pausz** [comment]
If we interpolated each draw over the range 15-49 years using `fpu.sigmoid_product`
![image](https://github.com/fpsim/fpsim/assets/1563810/ad629805-b4fa-4c36-b302-cc05355edb9c)

**Comment by mzimmermann-IDM** [comment]
Thanks for sharing @pausz these look great! Even the interpolation looks good. Could you add the point from the data to this so we can see how it compares? Or is the mean the same as the data?

**Comment by pausz** [comment]
You're right @mzimmermann-IDM, The black line labeled "mean +/- se" is actually the empirical data from the empowerment.csv. Probably should have labeled it as "empirical" ...

**Comment by pausz** [comment]
@mzimmermann-IDM I have a question about[ CFA.loadings.csv ](https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/CFA.loadings.csv)

In that file, there is an empowerment variable called `buy_decision_health`, but we do not have that variable in [empowerment.csv](https://github.com/fpsim/fpsim/blob/Kenya_empowerment_DHS/fpsim/locations/kenya/empowerment.csv). We have `decisionhealth`. 

Could it be that  `buy_decision_health` in CFA loadings corresponds to  `decisionhealth` ? I'd say yes, but I thought I double check with you first.

**Comment by mzimmermann-IDM** [comment]
Yes, it's the same @pausz ! Sorry about that.

**Comment by pausz** [comment]
Updated fig with all empowerment metrics  -- except composites 
![image](https://github.com/fpsim/fpsim/assets/1563810/3cd0025e-223e-43c2-b1e0-5536cc0df5a6)

**Comment by pausz** [comment]
With composites metrics. The background colour indicates the metric has been used to calculate one of the composite metrics: financial autonomy (blueish), or decision making (orangey).

@mzimmermann-IDM I noticed that the composite metrics can be > 1. Is this ok? or do we have to normalize them? 

![image](https://github.com/fpsim/fpsim/assets/1563810/dc581e0b-37c0-4691-b52f-d205454c80a0)

**Comment by mzimmermann-IDM** [comment]
@pausz beautiful!! I love these. The composite is supposed to be able to go >1 so that's perfect.
