### ISSUE TITLE
Plotting Age specific outcomes

### ISSUE THREAD

**Issue by nnoori-IDM** [fpsim/fpsim#347]
I have pulled the recent version of the FPsim and ran it on my laptop. When it comes to plotting the age specific results, it gives me the following error: 
    mcpr_fig = scens.plot('as_mcpr')

  File ~\OneDrive - Bill & Melinda Gates Foundation\Adolesents-FPsim\fpsim\fpsim\fpsim\scenarios.py:428 in plot
    return self.msim_merged.plot(to_plot=to_plot, plot_sims=plot_sims, **kwargs)

  File ~\OneDrive - Bill & Melinda Gates Foundation\Adolesents-FPsim\fpsim\fpsim\fpsim\sim.py:1318 in plot
    sim.plot(to_plot=to_plot, **kw, **kwargs)

  File ~\OneDrive - Bill & Melinda Gates Foundation\Adolesents-FPsim\fpsim\fpsim\fpsim\sim.py:704 in plot
    raise ValueError(f"Age specific plot selected but sim.pars['track_as'] is False")

ValueError: Age specific plot selected but sim.pars['track_as'] is False

I appreciate any help with fixing it.

**Comment by pausz** [comment]
Hi @nnoori-IDM 

I think it should work if you set `pars['track_as'] = True` 



For instance
```python

import fpsim as fp
 
n_agents   = [10_000, 100][debug]
start_year = [1980, 2010][debug]
track_as = True  #Track age-specific channels 
pars = fp.pars(n_agents=n_agents, start_year=start_year, end_year=2040, track_as=track_as)

# Define scenarios, etc ... 
```

**Comment by nnoori-IDM** [comment]
Thanks @pausz for your response. I tried it and it gave me the following error:

**AttributeError: module 'fpsim.defaults' has no attribute 'age_specific_results'**

Below is my code:
 pars = fp.pars(location='ethiopia')
 pars['n_agents'] = 50_000 # Small population size
 pars['start_year'] = 2010 
 pars['end_year'] = 2040 
 repeats = 10
 youth_ages = ['<18', '18-20']
 year     = 2022
 pars['low_age_short_int'] = 10 
 pars['high_age_short_int'] = 20 
 pars['track_as'] = True

 pp_method= ['Implants','Condoms','Pill']        
 kw1 = dict(method=pp_method[1],ages=youth_ages,matrix='pp0to1')
 kw2 = dict(method=pp_method[2],ages=youth_ages,matrix='pp0to1')
 kw3 = dict(method=pp_method[3],ages=youth_ages,matrix='pp0to1')
    
      
 implant1_4 = fp.make_scen(
            label = '1.4 times pp Implants initiation rate in <18 and 18-20',
            year=year,
            probs = [
                dict(init_factor=1.4, **kw1)
                    ]
                )
    
 condom1_4 = fp.make_scen(
            label = '1.4 times pp Condoms initiation rate in <18 and 18-20',
            year=year,
            probs = [
                dict(init_factor=1.4, **kw2)
                    ]
                )
    
 pill1_4 = fp.make_scen(
            label = '1.4 times pp Pill initiation rate in <18 and 18-20',
            year=year,
            probs = [
                dict(init_factor=1.4, **kw3)
                    ]
                )

 
 s1 = implant1_4 + condom1_4 + pill1_4
        
    #%% Create sims
 scens = fp.Scenarios(pars=pars,repeats=repeats)
 scens.add_scen(label='Baseline')
 scens.add_scen(s1,label="1.4 times PP Initiation Rate")

      # Run scenarios
 scens.run(serial=debug)
