### ISSUE TITLE
Check speed and look for optimizations

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#36]
From @avictorious :
> When I reset birth spacing preference probabilities to 1, running the model (like in example_sim.py) slows down by 3x!   This happens because more postpartum women are then set to be sexually active and have to run through check_conception at each time step, instead of being filtered off as not sexually active and irrelevant.  Code that’s responsible here: https://github.com/fpsim/fpsim/blob/1eaa4e6d023956de1790f9789b4d2c97902b37f2/fpsim/sim.py#L304-L317

**Comment by MObrien-IDM** [comment]
@cliffckerr - Is this issue still a priority for you? Let's close if not.

**Comment by cliffckerr** [comment]
Seems niche, ok to close.
