### ISSUE TITLE
Add ever use to simple choice module

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#361]
Once ever use is added as an attribute (issue #360), update simple choice contraceptive function to include this as well as age. Coefficients are attached.
[contra_coef_simple_pp1.csv](https://github.com/user-attachments/files/15960714/contra_coef_simple_pp1.csv)
[contra_coef_simple_pp6.csv](https://github.com/user-attachments/files/15960715/contra_coef_simple_pp6.csv)
[contra_coef_simple.csv](https://github.com/user-attachments/files/15960716/contra_coef_simple.csv)

**Comment by emilydriano** [comment]
this has been implemented in PR #359
