### ISSUE TITLE
Check & align logit (logistic?) probability calculations

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#368]
For a GLM of the form:

```
logit(p_t) = b0 + b1 * predictor_1 + b2 * predictor_2 + etc
```

Double check whether 
```
p_t = exp(rhs) / (1 + exp(rhs))
```

or 

```
p_t = 1 / (1  + exp(-rhs))
```

**Comment by mzimmermann-IDM** [comment]
Wow I'm glad to see I can solve this issue easily because these are these same thing! Everyone was right @pausz @robynstuart @emilydriano .

**Comment by emilydriano** [comment]
great! can this one be closed @mzimmermann-IDM ?

**Comment by pausz** [comment]
They indeed are. I should have noticed earlier :sweat_smile: . If we multiply and divide the first expression by exp(-rhs), we get the second expression :see_no_evil:.
