### ISSUE TITLE
Add interaction term for ever_used and age

### ISSUE THREAD

**Issue by emilydriano** [fpsim/fpsim#370]

**Comment by mzimmermann-IDM** [comment]
Done @emilydriano @robynstuart , here are the coefficients. 
[contra_coef_simple_pp1.csv](https://github.com/user-attachments/files/16152389/contra_coef_simple_pp1.csv)
[contra_coef_simple.csv](https://github.com/user-attachments/files/16152390/contra_coef_simple.csv)
[contra_coef_simple_pp6.csv](https://github.com/user-attachments/files/16152391/contra_coef_simple_pp6.csv)

**Comment by emilydriano** [comment]
thank you @mzimmermann-IDM! @robynstuart I've pushed these files to the methodtime-jun22 branch; could you add the interaction logic?

**Comment by robynstuart** [comment]
added on the `methodtime-jun22` branch
