### ISSUE TITLE
Tutorials for v2

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#400]
We need to create tutorials for the new version of the model. First, we want to recreate something similar to the tutorial we have in v1. We want to be able to change the efficacy of a method, to add a new method, or change the initiation, switching, or discontinuation for a method. We would like to be able to stratify by demographic variables. An example of this stratification would be a new method targeted at urban women age 20-25 who have 1+ children, are in the lowest wealth quintile, and have intent to use contraception.

We also want to add two new tutorials. One that increases the percentage of women who have intent to use contraception, and one that increases the percentage of women who are doing paid work.

**Comment by pausz** [comment]
Hi @mzimmermann-IDM. I've worked on a few simple tutorials:
- [T1 intro](https://github.com/fpsim/fpsim/blob/rc2.0-tuts-community-day/docs/tutorials/T1_intro.ipynb)
- [T2 intro to new modules](https://github.com/fpsim/fpsim/blob/rc2.0-tuts-community-day/docs/tutorials/T2_intro_to_new_features.ipynb)
- [T3 simple interventions to contraception methods dynamics](https://github.com/fpsim/fpsim/blob/rc2.0-tuts-community-day/docs/tutorials/T3_interventions.ipynb)
