### ISSUE TITLE
DMPA-SC Intervention

### ISSUE THREAD

**Issue by mzimmermann-IDM** [fpsim/fpsim#416]
Implement the intervention as follows:
- Baseline scenario: Increase % of women who are using contraception by 2% per year, so we need to increase initiation by 2% per year. Method mix stays the same.
- Intervention scenarios: Add two new methods: 3-month and 6-month DMA-SC, efficacy will be the same as injectables, time on method curve will be the same as injectables (for now, I might update that)
- Intervention scenario 1: a scale up of 3-month DMPA-SC from 1.5% at introduction (2025) to 5% by 2040 in women under age 20. 
- Intervention scenario 2: a scale up of 6-month DMPA-SC from 1% in 2030 up to 5% by 2040 in women under age 20.  26% of women on 3-month DMPA-SC and 20% of women on traditional methods will switch to 6-month DMPA-SC
- Intervention scenario 3: combined DMPA-SC scenario with both 3-month and 6-months scenarios implemented as above.

@MObrien-IDM Can you help clarify the initiation and switching method mixes? We can discuss tomorrow. 
![image](https://github.com/user-attachments/assets/6a417b32-c639-43ab-ae49-8cca3c54a408)

**Comment by pausz** [comment]
@mzimmermann-IDM I have a few of basic questions about the baseline scenario:

**Interpretation 1:** If the baseline percentage of women using contraception by the end of the first year of simulation is 50%, a  2% increase per year would result in 52% of women using contraception the next year and 54% the year after?

- And if the baseline percentage of women using contraception is expressed as a percentage, that would mean 50% of **women are eligible to use/choose** contraception, or 50% of all women in the population? 

  - subgroup of women who are by default eligible to use/choose contraception are women who (i) are aged < than the fecundity age limit; (ii) are sexually active (based on postpartum state or age); and (iii) are past their fated debut age.   

**Interpretation 2:** If the baseline number of women using contraception by the end of the first year is 100 women, a 2% increase per year would result in at least 102 of women using contraception the next year, and 104 the year after?

**Comment by mzimmermann-IDM** [comment]
@pausz interpretation 2. So it would be 
year 1 - 100
year 2 - 100*1.02 = 100.2
year 3 - 102*1.02 = 104.04
year 4 - 10404*1.02 = 106.1
Does that make sense?

**Comment by mzimmermann-IDM** [comment]
After talking with Michelle, we are going to redefine this a bit. 
- Baseline still the same as above, increasing 2% of injectable users each year. 
- Intervention scenario: we can just add one new intervention for DMPA-SC. It will be defined by:
- Initiation - some women who had the option to start using contraception but otherwise would not have started will not start and will use DMPA-SC. Placeholders: 5% of women in the year of the intervention, then 2% each year after.
- Switching - some women currently on injectables and traditional methods will switch to DMPA-SC. Placeholders (10% of injectable users and 5% of traditional method users).
- Discontinuation - The time on method curves for DMPA-SC will be longer than injectables. Placeholder: double the scale parameter.
Michelle and I are going to look for data sources to inform these numbers, so the above is placeholders. Let's talk through how we can do this this afternoon.
