### ISSUE TITLE
Tag management

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#427]
- [x] Tag & release v1.0.3
- [ ] Set up a GitHub action to tag + push to PyPI

**Comment by MObrien-IDM** [comment]
Thank you - @cliffckerr  can you prioritize this for before the methodtime branch is merged (i.e. in Dec 2024)?

**Comment by cliffckerr** [comment]
Done:
https://pypi.org/project/fpsim/1.0.4/

I didn't set up the GitHub action because it's a fair bit of work and can cause problems. But for posterity, here are the commands needed to release, say, version 2.0.0:
```bash
# create & push git tag
git tag v2.0.0
git push origin v2.0.0

# create & push pypi version
python -m build
twine upload dist/*
```

Anyone with write access to the FPsim repo can push a GitHub tag. Releasing a PyPI version requires, not surprisingly, a PyPI account. This is a very high-risk level of access so currently only a very small number of people are authorized to do this. I'm happy to do it whenever needed!
