### ISSUE TITLE
Refine workflow for calling different location parameters

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#45]
Test and figure out correct syntax for calling new country's parameters.  Desired syntax of fp.pars(location = 'kenya') is not currently working. 

fp.pars(location = 'kenya') is still running senegal parameters.  
Here is a side by side of the default plot from senegal vs kenya using the above syntax:

Kenya using fp.pars(location = 'kenya') 
![fpsim_kenya_location_syntax](https://user-images.githubusercontent.com/65202227/205083059-f41e3de4-41c6-4ea7-bb7e-6974173650ff.png)

Senegal using import fp.locations.senegal as sp;  sp.makepars() (the old way that was known to work)
![fpsim_senegal_make_pars](https://user-images.githubusercontent.com/65202227/205083970-4867af99-645b-499f-b161-2a40c9d63772.png)

import fpsim.locations.kenya.kenya as kp and kp.make_pars() does seem to be importing kenya.py parameters.  
Here is the resulting plot:

Kenya using import fp.locations.locations.kenya as kp;  kp.makepars()
![fpsim_kenya_using_make_pars](https://user-images.githubusercontent.com/65202227/205082656-a1e10669-dd99-4ff5-9f51-6f2cd5c1d0ae.png)

I did update location to 'kenya' under the scalar_pars() function in kenya.py

**Comment by cliffckerr** [comment]
Fixed by https://github.com/fpsim/fpsim/commit/3582681654d462bcd32d562150d8e8261d11c129
