### ISSUE TITLE
Reconsider docs branding

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#5]
The docs landing page is currently heavily IDM-branded.
- Pro: Shared template with other IDM docsets
- Con: May not advance our goals for this to be an IDM-sponsored, but inclusive and community-led effort. Personally, I would be disinclined to contribute open-source code to an org-branded repo (since I'd assume that their paid staff are taking care of it).

Options:
1. Leave as-is.
2. Keep IDM logo on every page, but make smaller and make the repo name bigger.
3. Keep the IDM logo, but move it to the welcome page rather than branding on every page.

![image](https://user-images.githubusercontent.com/3239256/199836756-a8214b75-5881-4196-b9f4-648c8c64762e.png)

**Comment by MObrien-IDM** [comment]
I like Option 3 the best.

**Comment by JSchripsema-IDM** [comment]
@MObrien-IDM The screenshot above is from an older template we switched from a few months ago (https://docs.idmod.org/projects/fpsim/en/latest/). Do you still want a smaller logo?

**Comment by cliffckerr** [comment]
I only just realized that now _only_ the IDM logo appears on the docs pages, not the name of the tool. But the tools don't have their own logos anyway, so maybe this makes sense for them? Other Python tools' doc pages use their own logo rather than the parent org's (e.g. [pandas](https://pandas.pydata.org/docs/index.html) is part of NumFocus, and [PyTorch](https://pytorch.org/docs/stable/index.html) is part of Linux).

**Comment by MObrien-IDM** [comment]
Right - We do need FPsim to show kind of prominently on the other pages (just clicking into tutorials and it's not super clear what the model is, just a big IDM logo). Is there a way to add FPsim under the IDM logo or something? To make sure that it's in the heading of each page?

**Comment by JSchripsema-IDM** [comment]
I took a look at the pydata theme options and we can add a "logo" setting under "html_theme_options" in docs/conf.py to include the project name in the header (https://github.com/pydata/pydata-sphinx-theme/blob/0ca99135b84e2a623382cf67b70d1e4bd96b2152/docs/conf.py#L191). You can see an example in their own docs here: https://pydata-sphinx-theme.readthedocs.io/en/stable/

**Comment by MObrien-IDM** [comment]
That would be great, Thanks @JSchripsema-IDM!

**Comment by cliffckerr** [comment]
Closed by #445
