### ISSUE TITLE
Formalize results export

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#63]
Should have nice `to_df()` methods, e.g. `msim.to_df()` that will package `msim.results` into a dataframe that can then be exported to Excel etc.

**Comment by MObrien-IDM** [comment]
Current solution to use msim is as follows:

df = scens.msim.to_df()
df.to_csv(r'filename')

This provides detailed results by timestep, plus a sim_label var that uses the scenario labeling.
