### ISSUE TITLE
Birth spacing and age at first birth - Kenya

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#68]
Need a raw data file from PMA or DHS that gives ages at all births to allow for calculating age at first birth and birth spaces. 

- [ ] Add code for processing file to "data_processing" folder in locations

@MObrien-IDM @cliffckerr I'm tagging both of you, whoever can help first or delegate to someone who can help wins.

**Comment by MObrien-IDM** [comment]
@mzimmermann-IDM  do you know where the processing code might be for this data from Senegal? I just went to recreate and realized that birth 1 in DHS is the most recent, and it moves backwards from there, which is frustrating. So, I'd rather not reinvent the wheel on birth spacing.

**Comment by avictorious** [comment]
@mzimmermann-IDM @MObrien-IDM trying to circle back to this.  I have the raw data file for the DHS birth spacing as it was done before here: https://raw.githubusercontent.com/fpsim/fp_prerelease/main/dropbox/BirthSpacing.csv?token=GHSAT0AAAAAAB4WUGTN2Y5673XWEVBLZZKAY6IFGIA

But I can't seem to find the old code for re-creating it.  I do know it's somewhere and think perhaps in Marita's github account?

**Comment by mzimmermann-IDM** [comment]
@avictorious I don't have the code for this but I'll just make it now. I don't seem to have access to that raw data file (says it doesn't exist). Can you tell me what to format should be?

**Comment by avictorious** [comment]
@mzimmermann-IDM Thanks so much for doing this.   The format for the csv is the following:
SurveyYear,caseid,Birth Order,Birth Spacing,v102
1986,     0101002002,0,21.5,urban
1986,     0101003003,0,19.5,urban
1986,     0101003006,0,17.5,urban
1986,     0101007004,0,19.916666666666668,urban
1986,     0101008002,0,22.166666666666668,urban
1986,     0101008007,0,20.0,urban
1986,     0101009002,0,18.916666666666668,urban
1986,     0101009010,0,16.833333333333332,urban
1986,     0101010007,0,23.166666666666668,urban
1986,     0101010012,0,19.833333333333332,urban
1986,     0101013002,0,25.5,urban
1986,     0102001014,0,16.583333333333332,urban
1986,     0102002009,0,17.25,urban
1986,     0102002011,0,19.833333333333332,urban
1986,     0102002014,0,18.5,urban
1986,     0102002025,0,18.416666666666668,urban
1986,     0102002029,0,18.5,urban

I'm not sure if PMA would be a useful place to get this data?  We could do both PMA and DHS like you did with the age-parity mix, or two different files from PMA and DHS.    

We don't really need survey year beyond the most recent 1-2 surveys since we're using this to calibrate to a model end state.  The two variables needed are birth order and birth spacing (reported in months).  Maybe not a bad idea to preserve the urban/rural info in case it's useful in the future.

**Comment by mzimmermann-IDM** [comment]
@avictorious Got it, thanks! Will do. And do you also need age at first birth? Is that a separate file?

**Comment by mzimmermann-IDM** [comment]
I see in your example rows that there are some birth order 0 rows with a birth interval.... does that imply this is the birth interval after that birth until the next birth? I always thin of birth interval as time since previous birth, but looks like this is opposite?

**Comment by mzimmermann-IDM** [comment]
Last question (for now!) is how you want to deal with weighting? I can't tell from the file how weights were incorporated, so it's up to you whatever is easiest to make your calibration figures. Right now I just have the weight as another variable for each row, and I normally apply the weights within my table or figure code. Let me know if you have a different approach.

**Comment by avictorious** [comment]
@mzimmermann-IDM Sorry, my comment about birth spacing being in months was confusing this issue.  It actually IS in years. 

The birth spacing file format lets me get the age at first birth and birth space all in one.  For birth order '0', that is the woman's first birth, and the birth space on those first order births is the years since her birthday, or how old she is at the first birth.   The other birth spaces are smaller numbers between the second order births.  Does that make sense?

For weights, it would be good if you could apply the weights to the values so they are weighted values.  Python/Pandas doesn't have any built in functionality to apply survey weights like R does so it's a little more klunky to have to do it during visualizations.   I usually apply the weight during my data processing step before I output the csv.  Is that possible here?

Also, were the skyscrapers data weighted? They came to me like this: 
age,parity,dataset,percentage
15-19,0,DHS 2014,15.3701174255872
15-19,0,PMA 2022,20.188612815085
15-19,1,DHS 2014,2.72898764722518
15-19,1,PMA 2022,2.46167173272213
15-19,2,DHS 2014,0.579901730307411
15-19,2,PMA 2022,0.180923794867296
15-19,3,DHS 2014,0.0403447214629128
15-19,3,PMA 2022,0.0377719088661704
15-19,4,DHS 2014,0.00643269409364071
20-24,0,DHS 2014,5.98882567503646
20-24,0,PMA 2022,7.71523353596203

I'm actually in the process of swapping out your weighted contraceptive matrices, I wanted to do the visualizations first with them unweighted to see how much of a difference it make in the calibration.

**Comment by mzimmermann-IDM** [comment]
Ohhhh got it, I didn't realize birth_spacing was age. I'll do it that way now.

Re: weighting. I'm happy to weight in the data processing stage, but how I do it depending on what you are going to do with the data. How are you summarizing or visualizing it? If I summarize the data before I give it to you, I can apply weight to that. For example, yes, the skyscrapers are weighted. So that means each of those percentages are sum(individual weights in the group)/total women, rather than sum(women in the group)/total women.

**Comment by mzimmermann-IDM** [comment]
Actually one more question before I get too far into this @avictorious . The PMA data is more limited than DHS because it does not have a full birth history. It has first birth, then births in the last 3 years (via contraceptive calendar data), so a lot of births are missing. Do you think it's still worth looking at in addition to DHS? There is also some weird data in the calendars, like having a births several months in a row or 1-2 month birth intervals, so we would have to just throw out those data points (its' about 40 of the 440 birth intervals we have in 3 rounds of Kenya data).

**Comment by avictorious** [comment]
@mzimmermann-IDM  Sorry I didn't see these questions!  Let's talk about weighting more.  I'm wondering if the Senegal data doesn't apply weights, looking at it again.  You're right that I'm using a raw dataset for Senegal that isn't summarized, just all the numbers of years between every birth in the DHS (starting with the age the woman was at her first birth).   I then summarize it into four spacing bins (<12 months, 12-24 months, 24-48 months, and > 48 months).   

If want to weight, we could do it in the processing code during the calibration, or you could create a file that already has the percentages in each spacing bin.   The second way would be a little simpler for future calibrations, the first way would be more flexible if we wants to compare continuous data instead of binned data during calibration.  I'm inclined to go with the second way.

**Comment by avictorious** [comment]
@mzimmermann-IDM For PMA data -- we could use it, but we would have to know it summarized all birth spaces in the last 3 years, not in the lifetime of the interviewed woman or agent.  So if we toggled to using PMA data in the model and wanted to use it to calibrate, we'd have to restrict the model to look at only the last 3 years of the agent's life. 

@MObrien-IDM do you want to comment on whether you want that flexibility with PMA?  If the data looks too out of left field to be cleaned and useful, it may not be worth it.

**Comment by MObrien-IDM** [comment]
Let's keep it simple with the DHS binned data, for now. We may want the flexibility in the future, but I don't think it is worth the extra effort at this point.

**Comment by avictorious** [comment]
This has been completed and was closed with a merge from Marita
