### ISSUE TITLE
Better name for file of ages of pregnant women in data

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#69]
This file: https://github.com/fpsim/fpsim/blob/main/fpsim/locations/senegal/SNIR80FL.obj   has a name that is suspiciously like a DHS individual recode file. 

When I examine the data frame that's loading from it in experiment.py, it looks to be a processed dataframe with 3 columns: age, a boolean currently pregnant or not variable, and a parity number.  Rows are the number of DHS respondents in the Senegal data. 

It would be good to 1) convert this to a csv so it's clearer what actual data is there  and 2) rename the file if it's truly a processed file so it doesn't appear to be a full DHS dataset.   I'd like to find the code that processed the data file too so I can put it back into the data_processing folder.

@cliffckerr can you help me understand if I'm looking at this correctly?  Could we convert this back to a csv and rename it?
@MObrien-IDM flagging you for visibility (this was designated as an asap issue to address)

**Comment by avictorious** [comment]
It looks like the original .obj may have been created in part by this file:

https://github.com/fpsim/fp_prerelease/blob/main/dropbox/preprocess_data.py
I don't think that script is being called anywhere within fpsim at this point so I think the .obj is already processed?

**Comment by MObrien-IDM** [comment]
Tagging @mzimmermann-IDM  as well, to see if she remembers anything about this file and its processing.

**Comment by mzimmermann-IDM** [comment]
I don't remember making or implementing this, unfortunately. What is it being used for? If it's just age, parity, and currently pregnant I could recreate that csv with reproducible code.

**Comment by MObrien-IDM** [comment]
Closed with #67
