### ISSUE TITLE
CPR - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#78]
Add CPR estimates and projections for Ethiopia by year. 
Senegal file reports on MCPR while Kenya's file reports on CPR. 

Format:
Year (1970-2030), CPR (any method)

**Comment by MObrien-IDM** [comment]
I would not use married women, since we explicitly and purposefully do not include marital status in the model.

**Comment by aaslinur** [comment]
That makes sense. I couldn't figure out how to produce estimates for all women using the online data portal, but with the full dataset downloaded from this page (https://www.un.org/development/desa/pd/data/family-planning-indicators) I was able to include estimates and projections for married women from 1970-1989 and for all women from 1990-2030, similar to the Kenya file.

**Comment by aaslinur** [comment]
Issue Resolved: PR #118
