### ISSUE TITLE
Method use for calibration year - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#83]
Create a file on method use for the desired calibrated year.

Format: 
Variable, Frequency, Percentage, Use

**Comment by MObrien-IDM** [comment]
@mzimmermann-IDM  - could you help out with this?

**Comment by mzimmermann-IDM** [comment]
Yep! From DHS, right? @aaslinur are you looking for total use, or for each method separately? Do you have a list of the methods to include, or just want everything DHS has? And can you explain the format a little more? It should be for each year, number of women, percentage of women (among users or total?), and something else?

**Comment by aaslinur** [comment]
@mzimmermann-IDM - I've been working on the method mix issue, which uses code from the data processing folder to produce estimates for method mix as well as method use from PMA data. For method use, the results are based on total use of any current method (1) vs no current method use (0). I have included the results for method use using the PMA Ethiopia 2019 Cross-sectional HQFQ Survey below. 

Var1 | Freq | perc | use
-- | -- | -- | --
-99 | 0.00207 | 0.207014 | NA
0 | 0.729299 | 72.92986 | No current method
1 | 0.268631 | 26.86313 | Any current method

Anything to add or consider based on your code @MObrien-IDM?

**Comment by aaslinur** [comment]
Issue Closed: PR #118

**Comment by aaslinur** [comment]
Data file updated to remove NA results for manual calibration

Var1 | Freq | perc | use
-- | -- | -- | --
0 | 0.729299 | 72.92986 | No current method
1 | 0.268631 | 26.86313 | Any current method
