### ISSUE TITLE
Skyscrapers data - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#86]
Produce skyscrapers data using R script in the data processing folder

- [x] pull in PMA data to run R script
- [x] add to locations/ethiopia folder

**Comment by aaslinur** [comment]
Based on the R script in the data processing folder, I have located the Individual Recode (ETIR71DT) dataset for the DHS Ethiopia 2016. It may be helpful to add comments that clarify which surveys and variables are needed to run this code.
 
The Kenya calibration pulls PMA data from the most recent phase of a cohort study, which uses the Household/Female (HQFQ) survey questionnaire. The longitudinal survey available for Ethiopia uses the HQFQ survey at baseline, then appears to use a Maternal Newborn Health focused questionnaire for the subsequent phases. 

- [ ] Need to look at the survey questionnaire to see if `birth_events` is captured in the same way in follow-up questionnaires.

**Comment by aaslinur** [comment]
`events_birth` is coded as `events_births_rw` in the codebook for Ethiopia
https://www.pmadata.org/sites/default/files/2022-03/PMAET_HQFQ_Master_Codebook_v28Feb2022_RELEASED.xlsx

Female/   Panel Follow-up Questionnaire: Reproduction & Fertility Preference   Questions |   |  
-- | -- | --
How many times have you given birth to a baby that was born alive? | birth_events_rw | number

**Comment by mzimmermann-IDM** [comment]
@aaslinur just edited this code for Ethiopia. Just realized I don't have the most recent Ethiopia PMA, so I requested it and am waiting for access. What branch are you working on? I can create a pull request for you to pull this code into you branch.

**Comment by aaslinur** [comment]
Issue Resolved: PR #118
