### ISSUE TITLE
Abortion probability - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#89]
Senegal parameter is based on the percentage of all pregnancies ending in abortion: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4712915/

**Comment by aaslinur** [comment]
Probability for Ethiopia found here: https://doi.org/10.1016/j.amsu.2022.104120  

Abortion rate is more commonly published than probability: https://osf.io/6t4eh

Have not come across enough data to produce an age-specific gradient, but there was a recent article on abortion among youth 15–24 in Ethiopia: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0248228

**Comment by MObrien-IDM** [comment]
The Yemane article looks like it is estimating the % of women who've terminated a pregnancy. Am I getting that right? If so, what we really need is % of pregnancies that end in abortion (since we're assessing the probability immediately after conception).

**Comment by aaslinur** [comment]
Yes, thank you for noting that. The most recent figure I found was from 2014: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5568682/

"The abortion ratio in 2014 was 17.6 abortions per 100 live births, indicating that there was approximately one abortion for every six pregnancies that ended in a live birth."

- [ ]  add to ethiopia.py script

**Comment by aaslinur** [comment]
Issue Closed: PR #156
