### ISSUE TITLE
Infant mortality rate - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#96]
Find array of infant mortality rate by year - used World Bank source for Senegal.

Plan to keep infant mortality age gradient for adolescents in place for Senegal. Gradient is reported for all of sub-Saharan Africa https://www.medrxiv.org/content/10.1101/2021.06.10.21258227v1

**Comment by MObrien-IDM** [comment]
@AMishra-IDM @aaslinur - Could we get an update on this task? Should be pretty straightforward to implement. Thank you!

**Comment by AMishra-IDM** [comment]
@aaslinur This is complete! Note that World Bank estimates for IMR do not start until 1966 for Ethiopia (compared to 1960 for Senegal).

**Comment by aaslinur** [comment]
Issue Closed: PR #156
